training:
    ############### you need to check every time #################
    num_epochs: 320
    batch_size: 1024
    learning_rate: 0.0008
    sample_per_ep: 32
    checkpoint_per_epoch: 32

    noise_level: 0.1
    ema: 0.9999 # only for const schedule
    ####################### end check ############################

    warmup_steps: 25000 # 20 ep for bs1024
    log_per_step: 100

    optimizer: adamw
    adam_b1: 0.9
    adam_b2: 0.95
    weight_decay: 0.0

    # ema_halflife_kimg: 500 # edm
    # wandb: False # use this to disable wandb

    ema_schedule: const # or edm
    lr_schedule: const
model:
    name: TSNF_Small_p2_b8_l8 # 118M
    teacher_dropout: 0.0
    student_dropout: 0.1
    # prior_norm: 0.5 # not supported now

    loss_weight: norm # options: norm, uniform
    label_drop_rate: 0.1
teacher: # for load teacher
    name: NF_Small_p2_b8_l8
    dropout: 0.0 # TODO: check this dp
fid:
    on_use: True
    fid_times: 10
    # num_samples: 50000 # 50k
    num_samples: 5000
    guidance: 0.0 # 0 for with label
    guidance_method: x
    # sanity_teacher: True

# load_teacher_from: /kmh-nfs-ssd-eu-mount/logs/sqa/sqa_Flow_matching/20250411_151116_hts34m_kmh-tpuvm-v3-32-1__b_lr_ep_torchvision_r50_eval/checkpoint_800640 # p2b8l8 160ep noise 0.05 # FID-5k: 86.4; IS-5k: 15.4
load_teacher_from: /kmh-nfs-ssd-eu-mount/logs/sqa/sqa_Flow_matching/20250418_141406_ksxsun_kmh-tpuvm-v3-32-13_sqa_NF/checkpoint_800640 # 1024bs, lr8e-4, noise0.1  640ep. # FID-5k: 67.67; IS-5k: 21.33

# load_from: /kmh-nfs-us-mount/logs/sqa/TS_imgnet/20250419_234424_52pr5f_kmh-tpuvm-v4-32-preemptible-yiyang__b_lr_ep_eval/checkpoint_237690 # student noise 0.05.
# load_from: /kmh-nfs-ssd-eu-mount/logs/sqa/TS_imgnet/20250428_152316_cuwdj3_kmh-tpuvm-v3-32-1__b_lr_ep_eval/checkpoint_387810 # teacher noise 0.1, dp0.1, ema0.9999.
# load_from: /kmh-nfs-ssd-eu-mount/logs/sqa/TS_imgnet/20250509_185212_juim3r_kmh-tpuvm-v3-32-1__b_lr_ep_eval # bs1024, noise0.1, jump2, dp0.1, ema0.9999
# load_from: /kmh-nfs-ssd-eu-mount/logs/sqa/TS_imgnet/20250511_174805_chimg9_kmh-tpuvm-v3-32-13__b_lr_ep_eval/checkpoint_240192 # resume, 1024bs, n0.1, jump2, dp0.1, ema0.9999, loss weight, half nan
# load_from: /kmh-nfs-ssd-eu-mount/logs/sqa/TS_imgnet/20250511_174805_chimg9_kmh-tpuvm-v3-32-13__b_lr_ep_eval/checkpoint_240192 # 1024bs, n0.1, jump2, dp0.1, ema0.9999, loss weight
load_from: /kmh-nfs-ssd-eu-mount/logs/sqa/TS_imgnet/20250511_195633_sv0ebv_kmh-tpuvm-v3-32-5__b_lr_ep_eval/checkpoint_320256 # 1024bs, n0.1, jump2, dp0.1, ema0.9999, loss weight, new cfg
search_cfg: True
just_evaluate: True # use this to just evaluate the model (without training)
# just_prior: True # teacher generate image, then student generate latent
save_by_fid: True

wandb_notes: "eval noise 0.1 T jump2 dp0.1 ema0.9999 loss weight new cfg"